# Meta Arguments: What job? What train .py file? Base config? Where to store?
meta_job_args:
    project_name: "crit-rnn"
    job_type: "hyperparameter-search"
    base_train_fname: "train_perturb_rnn.py"
    base_train_config: "configs/local_critical.json"
    experiment_dir: "experiments/local_grid"

# Parameters specific to the hyperparameter search
param_search_args:
    search_logging:
        reload_log: False
        verbose_log: True
        max_objective: True
        problem_type: "final"
        eval_metrics:
            - "train_acc"
            - "test_acc"
    search_resources:
        num_search_batches: 80
        num_evals_per_batch: 5
        num_seeds_per_eval: 5
    search_config:
        search_type: "grid"
        search_schedule: "sync"
        search_params:
            categorical:
                perturb_duration:
                    - 0.5
                max_center_distance:
                    - 3
                min_center_distance:
                    - 3
            real:
                a0:
                    begin: 1.0
                    end: 4.0
                    bins: 20
                w0:
                    begin: 1.0
                    end: 4.0
                    bins: 20

# Parameters specific to an individual job
single_job_args:
    job_name: "c"
    num_logical_cores: 6
    log_file: "log-c"
    err_file: "error-c"
    env_name: "criticality"
    time_per_job: "00:05:00"
    memory_per_job: "40000"
    exclude_nodes:
        - "cognition13"
        - "cognition14"
        - "cognition16"
